# Generated by Django 3.1.1 on 2020-11-24 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Infomation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('remark', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=30)),
                ('phone_No', models.CharField(max_length=15)),
                ('d_o_b', models.DateField()),
                ('password', models.CharField(max_length=70)),
                ('con_password', models.CharField(max_length=70)),
            ],
        ),
    ]
